- id: doi:10.1038/s41588-023-01441-8
  type: paper
  description: Aberrant RNA splicing events resulting from DNA variations are common causes of genetic disorders. Two studies published in Nature Genetics independently describe methods to decipher DNA-variant-associated aberrant splicing using high-throughput RNA sequencing data.
  date: 2020-12-4
  image: https://www.nature.com/articles/s41588-023-01363-5/figures/1
